<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdvancedMemory.Core\AdvancedMemory.Core.csproj" />
    <ProjectReference Include="..\AdvancedMemory.Shared\AdvancedMemory.Shared.csproj" />
  </ItemGroup>

</Project>
